/**
 * Seed script: Add 40 diverse Vietnamese food products for AI testing
 * Includes varied recipe ingredients and health tags for allergy detection testing
 * Run: npx ts-node -r tsconfig-paths/register src/seeds/product.seed.extra.ts
 */

import ProductModel from '@/models/product.model';
import FileModel from '@/models/file.model';
import connectToDatabase from '@/config/db';
import mongoose from 'mongoose';
import { ResourceType, FileOwnerType } from '@/types/file.type';

const extraProducts = [
  // ── HẢI SẢN (Seafood) ── sẽ trigger dị ứng hải sản
  {
    name: 'Cơm Hải Sản Xào Cay',
    category: 'com',
    description: 'Cơm chiên hải sản tươi với tôm, mực, nghêu xào cay kiểu Thái.',
    restaurant: 'Nhà Hàng Biển',
    price: 75000,
    rating: 4.7,
    review_count: 210,
    time: '15-20 min',
    imageUrl: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=500&h=500&fit=crop',
    tags: ['Spicy', 'Seafood'],
    health_tags: ['hải sản', 'shellfish'],
    recipe: [
      { name: 'Cơm', quantity: '200g' },
      { name: 'Tôm', quantity: '100g' },
      { name: 'Mực', quantity: '80g' },
      { name: 'Nghêu', quantity: '50g' },
      { name: 'Ớt', quantity: '10g' },
      { name: 'Dầu ăn', quantity: '20ml' },
    ],
    isAvailable: true,
  },
  {
    name: 'Bún Hải Sản Chua Cay',
    category: 'bun',
    description: 'Bún hải sản nước lèo chua cay đặc trưng miền Trung với tôm, cua, mực.',
    restaurant: 'Nhà Hàng Biển',
    price: 65000,
    rating: 4.6,
    review_count: 178,
    time: '15-20 min',
    imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=500&h=500&fit=crop',
    tags: ['Hot', 'Seafood'],
    health_tags: ['hải sản', 'tôm', 'cua'],
    recipe: [
      { name: 'Bún', quantity: '200g' },
      { name: 'Tôm', quantity: '80g' },
      { name: 'Cua', quantity: '60g' },
      { name: 'Mực', quantity: '60g' },
      { name: 'Rau thơm', quantity: '30g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Lẩu Tôm Chua Thái',
    category: 'com',
    description: 'Lẩu Tom Yum kiểu Thái với tôm sú, nấm, sả, lá chanh thơm nức.',
    restaurant: 'Thai Express',
    price: 180000,
    rating: 4.9,
    review_count: 390,
    time: '25-30 min',
    imageUrl: 'https://images.unsplash.com/photo-1562802378-063ec186a863?w=500&h=500&fit=crop',
    tags: ['Best Seller', 'Hot'],
    health_tags: ['hải sản', 'tôm'],
    recipe: [
      { name: 'Tôm sú', quantity: '200g' },
      { name: 'Nấm rơm', quantity: '100g' },
      { name: 'Sả', quantity: '30g' },
      { name: 'Riềng', quantity: '20g' },
      { name: 'Nước cốt dừa', quantity: '100ml' },
    ],
    isAvailable: true,
  },
  {
    name: 'Mì Hải Sản Nhật Bản',
    category: 'mi',
    description: 'Ramen hải sản phong cách Nhật với nước dùng miso đậm, tôm, mực, sò điệp.',
    restaurant: 'Ramen House',
    price: 95000,
    rating: 4.8,
    review_count: 267,
    time: '20-25 min',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&h=500&fit=crop',
    tags: ['Japanese', 'Seafood'],
    health_tags: ['hải sản', 'gluten'],
    recipe: [
      { name: 'Mì ramen', quantity: '150g' },
      { name: 'Tôm', quantity: '80g' },
      { name: 'Mực', quantity: '60g' },
      { name: 'Sò điệp', quantity: '40g' },
      { name: 'Tương miso', quantity: '30g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Gỏi Cuốn Tôm Thịt',
    category: 'com',
    description: 'Gỏi cuốn tươi mát với tôm luộc, thịt heo, bún, rau sống và nước chấm mè rang.',
    restaurant: 'Quán Việt',
    price: 45000,
    rating: 4.6,
    review_count: 145,
    time: '10-15 min',
    imageUrl: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=500&h=500&fit=crop',
    tags: ['Fresh', 'Healthy'],
    health_tags: ['hải sản', 'gluten'],
    recipe: [
      { name: 'Tôm', quantity: '60g' },
      { name: 'Thịt heo', quantity: '50g' },
      { name: 'Bún', quantity: '80g' },
      { name: 'Rau sống', quantity: '40g' },
      { name: 'Bánh tráng', quantity: '30g' },
      { name: 'Đậu phộng', quantity: '20g' },
    ],
    isAvailable: true,
  },

  // ── ĐẬU PHỘNG / NUTS (Peanut/Nut allergy)
  {
    name: 'Pad Thai Gà Đậu Phộng',
    category: 'mi',
    description: 'Pad Thai kiểu Thái với gà xào, đậu phụ, hành lá, giá đỗ và đậu phộng rang.',
    restaurant: 'Thai Express',
    price: 70000,
    rating: 4.7,
    review_count: 304,
    time: '15-20 min',
    imageUrl: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=500&h=500&fit=crop',
    tags: ['Thai', 'Popular'],
    health_tags: ['đậu phộng', 'nuts'],
    recipe: [
      { name: 'Mì gạo', quantity: '150g' },
      { name: 'Thịt gà', quantity: '100g' },
      { name: 'Đậu phộng', quantity: '30g' },
      { name: 'Giá đỗ', quantity: '50g' },
      { name: 'Trứng', quantity: '1 quả' },
    ],
    isAvailable: true,
  },
  {
    name: 'Gà Xào Sốt Đậu Phộng',
    category: 'com',
    description: 'Gà xào sốt đậu phộng kiểu Satay thơm béo, ăn kèm cơm trắng và dưa leo.',
    restaurant: 'Asian Kitchen',
    price: 75000,
    rating: 4.5,
    review_count: 189,
    time: '15-20 min',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500&h=500&fit=crop',
    tags: ['Popular'],
    health_tags: ['đậu phộng', 'nuts'],
    recipe: [
      { name: 'Thịt gà', quantity: '150g' },
      { name: 'Đậu phộng', quantity: '40g' },
      { name: 'Sữa dừa', quantity: '50ml' },
      { name: 'Cơm', quantity: '200g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Bánh Mì Kẹp Đậu Phộng Chuối',
    category: 'banh-mi',
    description: 'Bánh mì nướng giòn ăn kèm bơ đậu phộng, chuối thái lát và mật ong.',
    restaurant: 'Healthy Life',
    price: 35000,
    rating: 4.4,
    review_count: 98,
    time: '5-10 min',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500&h=500&fit=crop',
    tags: ['Healthy', 'Breakfast'],
    health_tags: ['đậu phộng', 'gluten'],
    recipe: [
      { name: 'Bánh mì', quantity: '1 ổ' },
      { name: 'Bơ đậu phộng', quantity: '30g' },
      { name: 'Đậu phộng', quantity: '15g' },
      { name: 'Chuối', quantity: '1 quả' },
    ],
    isAvailable: true,
  },

  // ── SỮA / LACTOSE
  {
    name: 'Kem Tươi Dâu Tây',
    category: 'drink',
    description: 'Kem tươi làm từ sữa bò nguyên chất với dâu tây tươi, ngọt thanh mát.',
    restaurant: 'Ice Cream Lab',
    price: 45000,
    rating: 4.8,
    review_count: 520,
    time: '5-10 min',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&h=500&fit=crop',
    tags: ['Sweet', 'Cold'],
    health_tags: ['sữa', 'lactose', 'dairy'],
    recipe: [
      { name: 'Kem sữa', quantity: '200ml' },
      { name: 'Sữa bò', quantity: '100ml' },
      { name: 'Dâu tây', quantity: '80g' },
      { name: 'Đường', quantity: '30g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Cafe Sữa Đá Truyền Thống',
    category: 'drink',
    description: 'Cà phê phin Việt đậm đà pha cùng sữa đặc, đá bào thơm ngon.',
    restaurant: 'Cafe Xưa',
    price: 30000,
    rating: 4.6,
    review_count: 867,
    time: '5-10 min',
    imageUrl: 'https://images.unsplash.com/photo-1559496417-e7f25cb247f3?w=500&h=500&fit=crop',
    tags: ['Classic', 'Cold'],
    health_tags: ['sữa', 'caffeine', 'dairy'],
    recipe: [
      { name: 'Cà phê', quantity: '30ml' },
      { name: 'Sữa đặc có đường', quantity: '40ml' },
      { name: 'Đá', quantity: '100g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Bánh Crepe Sữa Trứng',
    category: 'banh-mi',
    description: 'Crepe mỏng mềm làm từ sữa và trứng, nhân kem whipping và trái cây tươi.',
    restaurant: 'Bakery House',
    price: 55000,
    rating: 4.7,
    review_count: 234,
    time: '10-15 min',
    imageUrl: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=500&h=500&fit=crop',
    tags: ['Sweet', 'Dessert'],
    health_tags: ['sữa', 'trứng', 'gluten', 'dairy'],
    recipe: [
      { name: 'Bột mì', quantity: '100g' },
      { name: 'Sữa bò', quantity: '200ml' },
      { name: 'Trứng', quantity: '2 quả' },
      { name: 'Kem whipping', quantity: '80ml' },
      { name: 'Dâu tây', quantity: '60g' },
    ],
    isAvailable: true,
  },

  // ── GLUTEN / LÚA MÌ
  {
    name: 'Bánh Pizza Hải Sản',
    category: 'banh-mi',
    description: 'Pizza đế giòn với sốt cà chua, phô mai mozzarella, tôm, mực và ớt chuông.',
    restaurant: 'Pizza House',
    price: 150000,
    rating: 4.8,
    review_count: 445,
    time: '20-25 min',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&h=500&fit=crop',
    tags: ['Italian', 'Seafood'],
    health_tags: ['gluten', 'hải sản', 'sữa', 'dairy'],
    recipe: [
      { name: 'Bột mì', quantity: '200g' },
      { name: 'Phô mai', quantity: '100g' },
      { name: 'Tôm', quantity: '80g' },
      { name: 'Mực', quantity: '60g' },
      { name: 'Sốt cà chua', quantity: '50ml' },
    ],
    isAvailable: true,
  },
  {
    name: 'Bánh Mì Sandwich BLT',
    category: 'banh-mi',
    description: 'Sandwich bánh mì trắng với bacon, rau diếp, cà chua tươi và sốt mayo.',
    restaurant: 'Deli Corner',
    price: 55000,
    rating: 4.5,
    review_count: 167,
    time: '5-10 min',
    imageUrl: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?w=500&h=500&fit=crop',
    tags: ['Quick', 'Lunch'],
    health_tags: ['gluten'],
    recipe: [
      { name: 'Bánh mì trắng', quantity: '2 lát' },
      { name: 'Thịt xông khói', quantity: '60g' },
      { name: 'Sốt mayo', quantity: '20g' },
      { name: 'Rau diếp', quantity: '30g' },
      { name: 'Cà chua', quantity: '40g' },
    ],
    isAvailable: true,
  },

  // ── THUẦN CHAY / VEGAN-FRIENDLY
  {
    name: 'Bát Phật Chay Cao Cấp',
    category: 'com',
    description: 'Cơm gạo lứt hạt dài ăn kèm rau củ xào, đậu hũ chiên và nấm hương hầm.',
    restaurant: 'Healthy Life',
    price: 65000,
    rating: 4.7,
    review_count: 289,
    time: '15-20 min',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=500&fit=crop',
    tags: ['Vegan', 'Healthy'],
    health_tags: ['vegan', 'gluten-free'],
    recipe: [
      { name: 'Gạo lứt', quantity: '200g' },
      { name: 'Đậu hũ', quantity: '100g' },
      { name: 'Nấm hương', quantity: '80g' },
      { name: 'Bí xanh', quantity: '60g' },
      { name: 'Cà rốt', quantity: '50g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Salad Rau Củ Quả Tươi',
    category: 'com',
    description: 'Salad thập cẩm với rau xanh, cà chua bi, dưa leo, hạt quinoa và sốt chanh mật ong.',
    restaurant: 'Healthy Life',
    price: 55000,
    rating: 4.6,
    review_count: 198,
    time: '5-10 min',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=500&fit=crop',
    tags: ['Vegan', 'Fresh', 'Low Carb'],
    health_tags: ['vegan', 'gluten-free', 'low-calorie'],
    recipe: [
      { name: 'Rau xanh', quantity: '100g' },
      { name: 'Cà chua bi', quantity: '80g' },
      { name: 'Dưa leo', quantity: '60g' },
      { name: 'Quinoa', quantity: '50g' },
      { name: 'Chanh', quantity: '20ml' },
    ],
    isAvailable: true,
  },
  {
    name: 'Phở Chay Nấm Đặc Biệt',
    category: 'pho',
    description: 'Phở chay với nước dùng từ nấm shiitake, nấm rơm, sá sùng và các loại rau thơm.',
    restaurant: 'Phở Chay Tâm Đức',
    price: 50000,
    rating: 4.5,
    review_count: 134,
    time: '10-15 min',
    imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=500&h=500&fit=crop',
    tags: ['Vegan', 'Healthy'],
    health_tags: ['vegan', 'gluten-free'],
    recipe: [
      { name: 'Bánh phở', quantity: '200g' },
      { name: 'Nấm shiitake', quantity: '80g' },
      { name: 'Nấm rơm', quantity: '60g' },
      { name: 'Đậu hũ', quantity: '80g' },
      { name: 'Rau thơm', quantity: '30g' },
    ],
    isAvailable: true,
  },

  // ── BÒ / THỊT (Beef / Meat)
  {
    name: 'Bít Tết Bò Mỹ 200g',
    category: 'com',
    description: 'Steak bò Mỹ chín vừa, đi kèm khoai tây chiên và salad xanh tươi.',
    restaurant: 'Steak House Sài Gòn',
    price: 250000,
    rating: 4.9,
    review_count: 567,
    time: '20-25 min',
    imageUrl: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=500&h=500&fit=crop',
    tags: ['Premium', 'Chef Choice'],
    recipe: [
      { name: 'Thịt bò', quantity: '200g' },
      { name: 'Khoai tây', quantity: '150g' },
      { name: 'Bơ', quantity: '20g' },
      { name: 'Tỏi', quantity: '10g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Cơm Gà Xối Mỡ',
    category: 'com',
    description: 'Cơm trắng với gà ta xối mỡ vàng giòn, nước chấm gừng cay và dưa muối.',
    restaurant: 'Cơm Gà Bà Buội',
    price: 60000,
    rating: 4.8,
    review_count: 890,
    time: '10-15 min',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500&h=500&fit=crop',
    tags: ['Best Seller', 'Classic'],
    recipe: [
      { name: 'Gà', quantity: '200g' },
      { name: 'Cơm', quantity: '200g' },
      { name: 'Dầu chiên', quantity: '100ml' },
      { name: 'Gừng', quantity: '15g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Bánh Mì Thịt Nướng',
    category: 'banh-mi',
    description: 'Bánh mì giòn nhân thịt heo nướng, đồ chua, rau thơm và tương ớt.',
    restaurant: 'Bánh Mì Phượng',
    price: 30000,
    rating: 4.9,
    review_count: 1240,
    time: '5-10 min',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500&h=500&fit=crop',
    tags: ['Best Seller', 'Classic', 'Quick'],
    health_tags: ['gluten'],
    recipe: [
      { name: 'Bánh mì', quantity: '1 ổ' },
      { name: 'Thịt heo nướng', quantity: '80g' },
      { name: 'Đồ chua', quantity: '30g' },
      { name: 'Tương ớt', quantity: '15ml' },
    ],
    isAvailable: true,
  },
  {
    name: 'Bún Thịt Nướng Chả Giò',
    category: 'bun',
    description: 'Bún sợi nhỏ với thịt heo nướng, chả giò chiên vàng, rau sống và nước chấm chua ngọt.',
    restaurant: 'Quán Bún Ngon',
    price: 55000,
    rating: 4.7,
    review_count: 412,
    time: '10-15 min',
    imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=500&h=500&fit=crop',
    tags: ['Classic', 'Popular'],
    recipe: [
      { name: 'Bún', quantity: '200g' },
      { name: 'Thịt heo nướng', quantity: '80g' },
      { name: 'Chả giò', quantity: '40g' },
      { name: 'Rau sống', quantity: '50g' },
    ],
    isAvailable: true,
  },

  // ── TRỨNG / EGG ALLERGY
  {
    name: 'Cơm Chiên Trứng Thập Cẩm',
    category: 'com',
    description: 'Cơm chiên với 3 loại trứng (gà, vịt, cút), lạp xưởng và hành lá.',
    restaurant: 'Nhà Hàng Trung Hoa',
    price: 65000,
    rating: 4.6,
    review_count: 278,
    time: '10-15 min',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&h=500&fit=crop',
    tags: ['Popular', 'Filling'],
    health_tags: ['trứng', 'egg'],
    recipe: [
      { name: 'Cơm', quantity: '250g' },
      { name: 'Trứng gà', quantity: '2 quả' },
      { name: 'Trứng cút', quantity: '3 quả' },
      { name: 'Lạp xưởng', quantity: '50g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Bánh Trứng Sữa Custard',
    category: 'drink',
    description: 'Bánh trứng sữa custard kiểu Bồ Đào Nha, nhân kem vàng óng mịn, vỏ giòn.',
    restaurant: 'Bakery House',
    price: 25000,
    rating: 4.8,
    review_count: 634,
    time: '5-10 min',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&h=500&fit=crop',
    tags: ['Sweet', 'Dessert'],
    health_tags: ['trứng', 'sữa', 'gluten', 'dairy'],
    recipe: [
      { name: 'Trứng gà', quantity: '3 quả' },
      { name: 'Sữa tươi', quantity: '150ml' },
      { name: 'Bột mì', quantity: '80g' },
      { name: 'Đường', quantity: '60g' },
      { name: 'Bơ', quantity: '30g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Trứng Ốp La Bơ Thìa',
    category: 'com',
    description: 'Trứng ốp la vàng lòng đào, chiên bơ thơm, ăn kèm bánh mì nướng và cà chua bi.',
    restaurant: 'Breakfast Corner',
    price: 40000,
    rating: 4.5,
    review_count: 189,
    time: '5-10 min',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=500&fit=crop',
    tags: ['Breakfast', 'Quick'],
    health_tags: ['trứng', 'sữa', 'gluten'],
    recipe: [
      { name: 'Trứng gà', quantity: '2 quả' },
      { name: 'Bơ', quantity: '15g' },
      { name: 'Sữa', quantity: '30ml' },
      { name: 'Bánh mì', quantity: '2 lát' },
    ],
    isAvailable: true,
  },

  // ── KIM CHI / KOREAN
  {
    name: 'Cơm Trộn Bibimbap Bò',
    category: 'com',
    description: 'Bibimbap Hàn Quốc với thịt bò bắp xào, rau namul, trứng ốp la và tương gochujang.',
    restaurant: 'Seoul Kitchen',
    price: 110000,
    rating: 4.8,
    review_count: 445,
    time: '15-20 min',
    imageUrl: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=500&h=500&fit=crop',
    tags: ['Korean', 'Popular'],
    health_tags: ['gluten', 'trứng', 'sesame'],
    recipe: [
      { name: 'Cơm', quantity: '250g' },
      { name: 'Thịt bò', quantity: '100g' },
      { name: 'Kim chi', quantity: '60g' },
      { name: 'Trứng gà', quantity: '1 quả' },
      { name: 'Dầu mè', quantity: '10ml' },
    ],
    isAvailable: true,
  },
  {
    name: 'Tteokbokki Bánh Gạo Cay',
    category: 'com',
    description: 'Bánh gạo Hàn Quốc nấu sốt gochujang cay đậm, ăn kèm chả cá và hành lá.',
    restaurant: 'Seoul Kitchen',
    price: 85000,
    rating: 4.6,
    review_count: 312,
    time: '15-20 min',
    imageUrl: 'https://images.unsplash.com/photo-1562802378-063ec186a863?w=500&h=500&fit=crop',
    tags: ['Korean', 'Spicy', 'Trending'],
    health_tags: ['gluten'],
    recipe: [
      { name: 'Bánh gạo', quantity: '200g' },
      { name: 'Tương gochujang', quantity: '40g' },
      { name: 'Chả cá', quantity: '60g' },
      { name: 'Hành lá', quantity: '20g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Gà Rán Yangnyeom Hàn Quốc',
    category: 'com',
    description: 'Gà rán Hàn Quốc phủ sốt yangnyeom chua cay ngọt, giòn tan.',
    restaurant: 'Seoul Kitchen',
    price: 125000,
    rating: 4.9,
    review_count: 678,
    time: '20-25 min',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&h=500&fit=crop',
    tags: ['Korean', 'Best Seller', 'Crispy'],
    health_tags: ['gluten'],
    recipe: [
      { name: 'Gà', quantity: '300g' },
      { name: 'Bột chiên', quantity: '100g' },
      { name: 'Tương ớt Hàn', quantity: '40g' },
      { name: 'Mật ong', quantity: '20g' },
      { name: 'Tỏi', quantity: '10g' },
    ],
    isAvailable: true,
  },

  // ── ĂN NHẸ / SNACKS
  {
    name: 'Khoai Tây Chiên Phô Mai',
    category: 'com',
    description: 'Khoai tây chiên giòn phủ phô mai cheddar tan chảy và bacon bits.',
    restaurant: 'Snack Zone',
    price: 55000,
    rating: 4.4,
    review_count: 234,
    time: '10-15 min',
    imageUrl: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=500&h=500&fit=crop',
    tags: ['Snack', 'Comfort Food'],
    health_tags: ['sữa', 'dairy', 'gluten'],
    recipe: [
      { name: 'Khoai tây', quantity: '200g' },
      { name: 'Phô mai cheddar', quantity: '50g' },
      { name: 'Thịt xông khói', quantity: '30g' },
      { name: 'Dầu chiên', quantity: '50ml' },
    ],
    isAvailable: true,
  },
  {
    name: 'Chè Ba Màu Truyền Thống',
    category: 'drink',
    description: 'Chè ba màu đặc trưng Nam Bộ với đậu đỏ, đậu xanh, thạch, nước cốt dừa béo ngậy.',
    restaurant: 'Chè Ngon',
    price: 35000,
    rating: 4.7,
    review_count: 456,
    time: '5-10 min',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&h=500&fit=crop',
    tags: ['Sweet', 'Cold', 'Traditional'],
    health_tags: ['dairy', 'coconut'],
    recipe: [
      { name: 'Đậu đỏ', quantity: '80g' },
      { name: 'Đậu xanh', quantity: '80g' },
      { name: 'Nước cốt dừa', quantity: '100ml' },
      { name: 'Đường', quantity: '40g' },
      { name: 'Đá bào', quantity: '150g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Sinh Tố Bơ Sữa Mật Ong',
    category: 'drink',
    description: 'Sinh tố bơ mịn với sữa tươi không đường, mật ong nguyên chất và đá bào.',
    restaurant: 'Fruit Zone',
    price: 45000,
    rating: 4.6,
    review_count: 389,
    time: '5-10 min',
    imageUrl: 'https://images.unsplash.com/photo-1559496417-e7f25cb247f3?w=500&h=500&fit=crop',
    tags: ['Healthy', 'Cold'],
    health_tags: ['sữa', 'dairy'],
    recipe: [
      { name: 'Bơ', quantity: '200g' },
      { name: 'Sữa tươi', quantity: '150ml' },
      { name: 'Mật ong', quantity: '30ml' },
      { name: 'Đá', quantity: '100g' },
    ],
    isAvailable: true,
  },

  // ── MÌ / NOODLES
  {
    name: 'Mì Quảng Gà',
    category: 'mi',
    description: 'Mì Quảng chuẩn vị xứ Quảng với gà ta, tôm, rau sống và bánh tráng nướng.',
    restaurant: 'Quán Mì Quảng',
    price: 60000,
    rating: 4.8,
    review_count: 567,
    time: '10-15 min',
    imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=500&h=500&fit=crop',
    tags: ['Central Vietnam', 'Popular'],
    health_tags: ['gluten', 'hải sản'],
    recipe: [
      { name: 'Mì Quảng', quantity: '200g' },
      { name: 'Thịt gà', quantity: '100g' },
      { name: 'Tôm', quantity: '60g' },
      { name: 'Đậu phộng', quantity: '20g' },
      { name: 'Rau sống', quantity: '50g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Cao Lầu Hội An',
    category: 'mi',
    description: 'Cao lầu đặc sản Hội An với mì vàng thô, thịt xá xíu, tép mỡ giòn và rau địa phương.',
    restaurant: 'Quán Hội An',
    price: 70000,
    rating: 4.9,
    review_count: 445,
    time: '10-15 min',
    imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=500&h=500&fit=crop',
    tags: ['Hoi An', 'Heritage', 'Must Try'],
    health_tags: ['gluten'],
    recipe: [
      { name: 'Mì cao lầu', quantity: '200g' },
      { name: 'Thịt xá xíu', quantity: '80g' },
      { name: 'Tép mỡ', quantity: '30g' },
      { name: 'Rau sống', quantity: '50g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Mì Xào Bò Gừng',
    category: 'mi',
    description: 'Mì xào giòn với thịt bò mỏng, gừng tươi, ớt chuông và hành tây xào.',
    restaurant: 'Nhà Hàng Trung Hoa',
    price: 80000,
    rating: 4.6,
    review_count: 223,
    time: '15-20 min',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&h=500&fit=crop',
    tags: ['Chinese', 'Quick'],
    health_tags: ['gluten'],
    recipe: [
      { name: 'Mì trứng', quantity: '150g' },
      { name: 'Thịt bò', quantity: '120g' },
      { name: 'Gừng', quantity: '15g' },
      { name: 'Ớt chuông', quantity: '60g' },
      { name: 'Dầu hào', quantity: '20ml' },
    ],
    isAvailable: true,
  },

  // ── BURGER
  {
    name: 'Burger Bò Phô Mai Double',
    category: 'com',
    description: 'Double burger hai lớp thịt bò Mỹ, phô mai cheddar, sốt đặc biệt và dưa cải.',
    restaurant: 'Burger Lab',
    price: 120000,
    rating: 4.8,
    review_count: 567,
    time: '15-20 min',
    imageUrl: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=500&h=500&fit=crop',
    tags: ['American', 'Best Seller'],
    health_tags: ['gluten', 'sữa', 'dairy'],
    recipe: [
      { name: 'Bún burger', quantity: '1 cái' },
      { name: 'Thịt bò xay', quantity: '200g' },
      { name: 'Phô mai cheddar', quantity: '40g' },
      { name: 'Sốt burger', quantity: '30ml' },
      { name: 'Dưa cải', quantity: '30g' },
      { name: 'Cà chua', quantity: '40g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Burger Gà Giòn Cay',
    category: 'com',
    description: 'Burger gà rán giòn với sốt cay đặc biệt, bắp cải bào, dưa cải và mayo.',
    restaurant: 'Burger Lab',
    price: 95000,
    rating: 4.7,
    review_count: 412,
    time: '15-20 min',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&h=500&fit=crop',
    tags: ['Spicy', 'Popular', 'Crispy'],
    health_tags: ['gluten'],
    recipe: [
      { name: 'Bún burger', quantity: '1 cái' },
      { name: 'Ức gà chiên', quantity: '150g' },
      { name: 'Bột chiên xù', quantity: '50g' },
      { name: 'Sốt cay', quantity: '25ml' },
      { name: 'Mayo', quantity: '20ml' },
    ],
    isAvailable: true,
  },

  // ── SOUP / CANH
  {
    name: 'Súp Kem Nấm Truffle',
    category: 'drink',
    description: 'Súp kem nấm trắng hấp dẫn với truffle oil, kem tươi và bánh mì nướng bơ.',
    restaurant: 'Fine Dining',
    price: 95000,
    rating: 4.8,
    review_count: 167,
    time: '10-15 min',
    imageUrl: 'https://images.unsplash.com/photo-1559496417-e7f25cb247f3?w=500&h=500&fit=crop',
    tags: ['Premium', 'Comfort Food'],
    health_tags: ['sữa', 'gluten', 'dairy'],
    recipe: [
      { name: 'Nấm trắng', quantity: '150g' },
      { name: 'Kem tươi', quantity: '100ml' },
      { name: 'Sữa', quantity: '100ml' },
      { name: 'Bơ', quantity: '20g' },
      { name: 'Truffle oil', quantity: '5ml' },
    ],
    isAvailable: true,
  },
  {
    name: 'Canh Chua Cá Lóc',
    category: 'com',
    description: 'Canh chua miền Nam với cá lóc, thơm, cà chua, giá đỗ và me chua dậy mùi.',
    restaurant: 'Cơm Nhà',
    price: 65000,
    rating: 4.7,
    review_count: 345,
    time: '15-20 min',
    imageUrl: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=500&h=500&fit=crop',
    tags: ['Southern Vietnam', 'Homemade', 'Traditional'],
    health_tags: ['hải sản', 'fish'],
    recipe: [
      { name: 'Cá lóc', quantity: '300g' },
      { name: 'Thơm', quantity: '100g' },
      { name: 'Cà chua', quantity: '80g' },
      { name: 'Me', quantity: '30g' },
      { name: 'Giá đỗ', quantity: '60g' },
    ],
    isAvailable: true,
  },

  // ── PREMIUM / ĐẶC BIỆT
  {
    name: 'Sushi Cá Hồi Moriawase',
    category: 'com',
    description: 'Set sushi 12 miếng cao cấp với cá hồi, cá ngừ, tôm, surimi và trứng cá hồi.',
    restaurant: 'Sushi Nakamura',
    price: 280000,
    rating: 4.9,
    review_count: 234,
    time: '15-20 min',
    imageUrl: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=500&h=500&fit=crop',
    tags: ['Japanese', 'Premium', 'Seafood'],
    health_tags: ['hải sản', 'cá', 'gluten'],
    recipe: [
      { name: 'Cá hồi', quantity: '80g' },
      { name: 'Cá ngừ', quantity: '60g' },
      { name: 'Tôm', quantity: '60g' },
      { name: 'Cơm sushi', quantity: '200g' },
      { name: 'Rong biển', quantity: '20g' },
      { name: 'Wasabi', quantity: '10g' },
    ],
    isAvailable: true,
  },
  {
    name: 'Cơm Rang Hải Sản Hoàng Gia',
    category: 'com',
    description: 'Cơm rang thập cẩm hải sản cao cấp với tôm hùm, sò điệp, cua và trứng cá hồi.',
    restaurant: 'Royal Kitchen',
    price: 350000,
    rating: 4.9,
    review_count: 89,
    time: '25-30 min',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&h=500&fit=crop',
    tags: ['Premium', 'Chef Choice', 'Seafood'],
    health_tags: ['hải sản', 'shellfish', 'tôm', 'cua'],
    recipe: [
      { name: 'Cơm', quantity: '250g' },
      { name: 'Tôm hùm', quantity: '100g' },
      { name: 'Sò điệp', quantity: '80g' },
      { name: 'Cua', quantity: '100g' },
      { name: 'Trứng cá hồi', quantity: '30g' },
      { name: 'Trứng gà', quantity: '2 quả' },
    ],
    isAvailable: true,
  },
  {
    name: 'Bò Nhúng Dấm Mâm Đầy',
    category: 'com',
    description: 'Bò nhúng giấm cuốn bánh tráng với rau thơm, bún tươi, chấm mắm nêm.',
    restaurant: 'Tiệm Bò Việt',
    price: 175000,
    rating: 4.8,
    review_count: 312,
    time: '20-25 min',
    imageUrl: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=500&h=500&fit=crop',
    tags: ['Premium', 'Southern Vietnam'],
    recipe: [
      { name: 'Thịt bò', quantity: '300g' },
      { name: 'Bánh tráng', quantity: '50g' },
      { name: 'Rau thơm', quantity: '80g' },
      { name: 'Bún tươi', quantity: '150g' },
      { name: 'Dấm', quantity: '50ml' },
    ],
    isAvailable: true,
  },
  {
    name: 'Hủ Tiếu Nam Vang',
    category: 'bun',
    description: 'Hủ tiếu khô hoặc nước theo yêu cầu với tôm, thịt xay, gan heo và hành phi.',
    restaurant: 'Hủ Tiếu Nam Vang',
    price: 60000,
    rating: 4.7,
    review_count: 523,
    time: '10-15 min',
    imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=500&h=500&fit=crop',
    tags: ['Classic', 'Popular'],
    health_tags: ['hải sản', 'gluten'],
    recipe: [
      { name: 'Hủ tiếu', quantity: '200g' },
      { name: 'Tôm', quantity: '60g' },
      { name: 'Thịt xay', quantity: '80g' },
      { name: 'Gan heo', quantity: '40g' },
      { name: 'Hành phi', quantity: '15g' },
    ],
    isAvailable: true,
  },
];

async function seedExtraProducts() {
  try {
    await connectToDatabase();
    console.log('📦 Starting to seed 40 extra products...');

    const products = [];

    for (const item of extraProducts) {
      const productId = new mongoose.Types.ObjectId();
      const { imageUrl, ...productData } = item as any;

      const file = await FileModel.create({
        public_id: `product_extra_${productId}_${Date.now()}`,
        secure_url: imageUrl,
        resource_type: ResourceType.IMAGE,
        width: 500,
        height: 500,
        bytes: 1024,
        format: 'jpg',
        folder: 'products',
        owner_id: productId,
        owner_type: FileOwnerType.PRODUCT,
      });

      products.push({
        _id: productId,
        ...productData,
        image: file._id,
      });
    }

    const result = await ProductModel.insertMany(products);
    console.log(`✅ Successfully seeded ${result.length} extra products!`);
    console.log(`📊 Categories: com, bun, mi, pho, drink, banh-mi`);
    console.log(`🥜 Allergy tags: hải sản, đậu phộng, sữa, gluten, trứng`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding extra products:', error);
    process.exit(1);
  }
}

seedExtraProducts();
